# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-TiVo
version:      0.08
version_from: lib/Net/TiVo.pm
installdirs:  site
requires:
    Log::Log4perl:                 0
    LWP::UserAgent:                2
    XML::Simple:                   2.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
